### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by SalahAdDin** [muk-it/muk_base#3]
Hello, i'm testing this wonderful addon's pack.

I got an error trying to install `MSOffice preview`: `unoconv`.

I think it would be great if you can provide us more detailed documentation.

**Comment by keshrath** [comment]
Hello, have you already read: https://github.com/muk-it/muk_base/blob/11.0/muk_converter/doc/index.rst

**Comment by SalahAdDin** [comment]
@keshrath must we have installed Libreoffice?

**Comment by keshrath** [comment]
Yes, but you can using it with no X display.

https://github.com/dagwieers/unoconv#using-unoconv-with-no-x-display

**Comment by SalahAdDin** [comment]
We want to use it without any `libreoffice` window or whatever, but as far i can see `unoconv` works well as backend script, thank you.

**Comment by SalahAdDin** [comment]
@keshrath I saw there are some dependencies for `thumbnails`, for example, that are not in the documentation.

**Comment by keshrath** [comment]
What did I miss?

From the documentation:

Requirements

Unoconv
Universal Office Converter (unoconv) is a command line tool to convert any document format that LibreOffice can import to any document format that LibreOffice can export. It makes use of the LibreOffice's UNO bindings for non-interactive conversion of documents.

To install unoconv please follow the instructions (here).

Make sure that unoconv can be executed from the console and the conversion is done correctly.

To set an individual path for the LibreOffice installation, the config variable uno_path can be set accordingly in the Odoo config.

Under Windows you should rename the unoconv file to unoconv.py and set the corresponding path for the uno_path variable. Since it does not work reliably with the environment variable UNO_PATH.

FFmpeg
FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video.

To install FFmpeg please follow the instructions (here).

Ghostscript
Ghostscript is a suite of software based on an interpreter for Adobe Systems PostScript and Portable Document Format (PDF) page description languages. Its main purposes are the rasterization or rendering of such page description language files, for the display or printing of document pages, and the conversion between PostScript and PDF files.

To install Ghostscript please follow the instructions (here).

ImageMagick
ImageMagick can be used to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, GIF, HEIC, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bezier curves.

To install ImageMagick please follow the instructions (here).

Source: https://github.com/muk-it/muk_base/blob/11.0/muk_thumbnails/doc/index.rst

**Comment by SalahAdDin** [comment]
Those: `imageio`, `moviepy` and `Wand`.

**Comment by keshrath** [comment]
imageio is installed with moviepy and the are listed here: https://github.com/muk-it/muk_base/blob/11.0/muk_thumbnails/__manifest__.py

**Comment by keshrath** [comment]
But you are right its a good idea to add them in den doc as well :)

**Comment by SalahAdDin** [comment]
Thank you very much, i just got them because i got many warnings in console.

**Comment by keshrath** [comment]
29a1cbfc1373feaf0b861d0aa4b34ebb218fd772
